### PR TITLE
WIP: Rework game controls and sidebar UI

### PR DESCRIPTION
**Pull request by alcalyn**

### CODE REVIEW

**Comment by eilvelia** [comment]
I think the check/warning icons in the rules are pretty redundant

**Comment by eilvelia** [comment]
(Also perhaps "normal" can be removed, and shown only if there are actually exceptions to the rules.)

**Comment by ursi** [comment]
I think confirmation settings should be accessible here as well. maybe just the setting for the time category you're currently playing.

**Comment by alcalyn** [comment]
Ah yes, adding a shortcut to change move confirm setting is a good idea! Hadn't thought of that

**Comment by alcalyn** [comment]
"I have no idea what I'm doing"
Capture d’écran 2024-10-04 à 22 50 32

**Comment by alcalyn** [comment]
I have something that seems ok! Also:

- removed warning on game rules
- added a way to change "confirm move" setting

**Comment by ursi** [comment]
image
only 2 of 3 rotation options are available? (also text and icons need better alignment)

**Comment by alcalyn** [comment]
Yes it was to keep it minimal, I didn't wanted to remake all the setting page here. But ok maybe it's weird, if you use the other orientation (flat 2), you cannot try an other one, and come back to your initial orientation

**Comment by ursi** [comment]
The collapsed graph should change the cursor to the hand when it's moused over, to indicate clickability. I can probably do this myself today after work, but I wanted to document it.

**Pull request merged**
